apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dtxaw7yhe-nodejs 
  janus-idp.io/tekton: dtxaw7yhe-nodejs
  backstage.io/kubernetes-id: dtxaw7yhe-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dtxaw7yhe-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml